# Generated by Django 4.2.19 on 2025-04-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_meditationsession_duration_meditationsession_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditationsession",
            name="background_noise",
            field=models.CharField(
                choices=[("rainy", "Rainy"), ("piano", "Piano"), ("fire", "Fire")],
                default="rainy",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="meditationsession",
            name="voice",
            field=models.IntegerField(
                choices=[
                    (1, "Voice 1"),
                    (2, "Voice 2"),
                    (3, "Voice 3"),
                    (4, "Voice 4"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="meditationsession",
            name="duration",
            field=models.IntegerField(default=1),
        ),
    ]
