# Generated by Django 4.2.19 on 2025-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_meditationsession_background_noise_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meditationsession",
            name="audio_file",
            field=models.FileField(blank=True, null=True, upload_to="sessions/audio/"),
        ),
        migrations.AlterField(
            model_name="meditationsession",
            name="voice",
            field=models.CharField(
                choices=[
                    ("shimmer", "Shimmer"),
                    ("echo", "Echo"),
                    ("sage", "Sage"),
                    ("alloy", "Alloy"),
                    ("ash", "Ash"),
                    ("ballad", "Ballad"),
                    ("coral", "Coral"),
                    ("verse", "Verse"),
                ],
                default="sage",
                max_length=20,
            ),
        ),
    ]
