# Generated by Django 4.2.19 on 2025-04-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_meditationsession_audio_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="favoritesession",
            unique_together={("user", "session")},
        ),
    ]
